### ISSUE TITLE
perm expressions are not known to be non-negative when applied to predicates

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#171]
> Created by **@alexanderjsummers** on 2017-01-06 20:50
> Last updated on 2019-11-29 13:35

For example, the following line will typically fail (but should always succeed):

```
#!scala
exhale forall r:Ref :: r != null ==> acc(p(r),perm(p(r)))
```

**Comment by gauravpartha** [comment]
Fixed in 3b58d4f.
