### ISSUE TITLE
test case quantifiedpredicates/issues//block_array.sil is sporadically timing-out (on the build server)

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#176]
> Created by **@alexanderjsummers** on 2017-01-15 14:52
> Last updated on 2017-02-13 16:08

This seems likely to be related to the changes in commit <https://github.com/viperproject/carbon/commit/ba8943897661d3169bc57fc9b99fbf41bae7cb32>

**Comment by fabiopakk** [comment]
This issue is no longer reproducible after stress test both on the build server and locally. From the opening date to today we addressed several such issues and adopted the use of stable versions of Z3 which might have been the root cause behind this issue.
