### ISSUE TITLE
Perm expressions are not correctly sensitive to outer unfolding expressions

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#213]
> Created by **@alexanderjsummers** on 2017-08-08 14:46
> Last updated on 2020-02-17 16:53

The attached example illustrates the problem. In the code, an unfolding expression is ultimately evaluated just to its body; the actual unfold operation is only considered for well-definedness checking.

---

Attachments:
* [**`0213.sil`**](https://gist.githubusercontent.com/viper-admin/a5c65daf354cd420c80df6549032f02e/raw/d0c6201b21e5c96159d59f5032db6a26324c1aa6/0213.sil)

**Comment by gauravpartha** [comment]
This particular example has been solved by https://github.com/viperproject/carbon/commit/1e2a95ec6b3ffe8385b2810ea6a02d87a9343e25. However, there are still related issues, see https://github.com/viperproject/carbon/issues/348 for a more detailled discussion.
