### ISSUE TITLE
Runtime Exception When Using `wildcard` as Predicate Parameter

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#235]
> Created by bitbucket user **ntruessel** on 2018-05-16 16:11

When using `wildcard` as a parameter to a predicate, carbon crashes
with a runtime exception. See the attachment for a minimal crashing example.

---

Attachments:
* [**`predicate-wildcard.vpr`**](https://gist.githubusercontent.com/viper-admin/8d4f512a8855700dd24ec96489903809/raw/a9136ff770a6648d9c6ba976a75666a71b27b618/predicate-wildcard.vpr)

**Comment by gauravpartha** [comment]
Duplicate of #169.
