### ISSUE TITLE
Using magic wands inside predicates or preconditions of functions is not supported

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#244]
> Created by bitbucket user **abdelzaher** on 2018-06-21 15:34

Currently using Magic wands inside predicates or functions preconditions will give runtime error. Magic wands snapshots should be supported first in order to support using magic wands in predicates and functions preconditions.

**Comment by mschwerhoff** [comment]
I suggest rejecting unsupported programs via a consistency check in Carbon. Currently, a `ClassCastException` is thrown, e.g. for

```
function req_wand(a: Ref): Int
  requires true --* true
```

**Comment by fabiopakk** [comment]
@mschwerhoff  and @maurobringolf:
Would you suggest rejecting this unsupported program via a consistency check in Carbon or reject in Silver altogether? In the former case, we favor the homogeneity of results among backends. Which one is preferred? Thanks.

**Comment by fabiopakk** [comment]
Please check viperproject/silver#478 for consistently solving all aspects of this issue, as it also involves Silver and Silicon, and not just Carbon.
