### ISSUE TITLE
Support Z3 > 4.8.6 (probably a Boogie issue)

### ISSUE THREAD

**Issue by mschwerhoff** [viperproject/carbon#357]
Using the same Boogie version as used by Carbon on Jenkins, I get Boogie errors for Z3 4.8.7, 4.8.8 and 4.8.9.nightly. It seems that Boogie emits Z3 configuration options that are no longer valid.

I would have filed a Boogie issue, but I'm not sure how recent the Boogie version we use (on Jenkins) actually is.

**Comment by gauravpartha** [comment]
The newest Boogie version should be compatible with the new Z3 versions, i.e., the configuration options have been updated.

We are using an old Boogie version (which still emits the old Z3 configuration options), because the way Boogie is set up right now we can't test it reliably. Alex and I are trying to make the Boogie test reliably, so that we can then update Carbon to use the newest Boogie version.

**Comment by gauravpartha** [comment]
@mschwerhoff If it is useful for you, I could create a fork of Carbon that works with the newest Boogie version (if one just forces Carbon to use the newest Boogie version, then it won't work, due to Boogie configuration options being different).

**Comment by mschwerhoff** [comment]
I don't often run Carbon locally, so creating a fork just for me won't be necessary. Nonetheless, thank you for the explanation and the offer.

**Comment by alexanderjsummers** [comment]
This works in the newly-released Viper version, right? @gauravpartha

**Comment by gauravpartha** [comment]
> 
> 
> This works in the newly-released Viper version, right? @gauravpartha

We have not included the new Boogie release in the newly-released Viper version, so the situation is the same. But in the next release a new Boogie release should be included.

**Comment by gauravpartha** [comment]
This should not be an issue anymore. Carbon has been updated to invoke Boogie differently that is compatible with newer Boogie versions. As a result, newer versions of Z3 can be used. However, there seem to be verification issues with Z3 4.8.9 that we need to debug.
