### ISSUE TITLE
Add well-definedness checks for built-in axiomatisations

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#36]
> Created by **@alexanderjsummers** on 2014-11-10 16:57
> Last updated on 2020-02-03 13:35

The sequence, set, multiset axioms have implicit preconditions on certain operations (e.g., drop from a sequence is only axiomatised in the case in which the index is non-negative). We should either make the axioms more permissive, or add well-definedness checks which ensure that these conditions hold at use-site. These checks should be made consistently in both Silicon and Carbon.

**Comment by alexanderjsummers** [comment]
If I understand correctly, we made the axioms more complete; we don't add well-definedness restrictions but instead have axioms which tell us something even when dropping too many elements, etc.
