### ISSUE TITLE
Strange macro-related error

### ISSUE THREAD

**Issue by tdardinier** [viperproject/carbon#370]
Expanding the macro `write * 2` as in the following example

```
define two (write * 2)

method main() {
    assert two > none
}
```

fails with the following error message:

> Parse error: Macro expansion would result in invalid code (encountered ParseTreeDuplicationError:
> Cannot duplicate viper.silver.parser.PBinExp@82dc0e45 with new children List(PFullPerm(), *, PIntLit(2)) (test.vpr@4.15)

**Comment by marcoeilers** [comment]
Whatever this was, it works fine now, so I'll close this.
