### ISSUE TITLE
"cannot translate wildcard at an arbitrary position" when multiplying with wildcard

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/carbon#376]
I have a problem similar to #169, where a runtime exception is thrown with the error:

```
Exception in thread "main" java.lang.RuntimeException: cannot translate wildcard at an arbitrary position (should only occur directly in an accessibility predicate)
```

It happens on carbon master with the following input:

```scala
//  a field 
field Node_rank: Int

method Main_parrallel_region_main_1_Sequence$Node$_EncodedGlobalVariables(diz: Ref, nodes: Seq[Ref])
  requires 0 < |nodes| ==> (forall j: Int :: { nodes[j].Node_rank } 0 <= j && j < |nodes| ==> acc(nodes[j].Node_rank, |nodes| * wildcard))
{
  inhale false
}
```

Silicon seems to verify it without problems. Will multiplication with wildcards be unsupported in the future, or is this an instance of #169?

**Comment by gauravpartha** [comment]
I don't think it's an instance of #169, but rather to #85. It seems that Carbon only supports multiplication of wildcards if it can be trivially determined that the other factor is strictly positive. I'll bring this topic up in the next meeting with the Viper team (which is next month) and then report here on whether this should be supported or not.

It would be interesting to know why such multiplications show up in your encoding and whether you have feasible workarounds. Could you elaborate on that, please?

**Comment by marcoeilers** [comment]
I'll close this, since compound expressions involving wildcards are prevented by a consistency check since https://github.com/viperproject/silver/pull/700. We're not planning to support multiplication or any other arithmetic involving wildcards in the future.
