### ISSUE TITLE
Injectivity check for quantified predicates missing

### ISSUE THREAD

**Issue by mschwerhoff** [viperproject/carbon#378]
Consider the following program:

```plain
predicate p(a: Ref, b: Ref)

method m(x: Ref, s: Set[Ref], t: Seq[Ref]) {
  exhale forall a: Int, b: Ref :: b in s && 0 <= a && a < |t| ==> p(t[a], b) // might not be injective
}
```

The QP assertion may not be injective in the predicate arguments (which Silicon reports), but Carbon only reports potentially insufficient permissions.

**Comment by marcoeilers** [comment]
Turns out the injectivity check was not actually missing, but just incorrect (also for fields); see the explanation in PR #542 that fixes this.
