### ISSUE TITLE
Crashes because of function call under an existential inside a function body

### ISSUE THREAD

**Issue by tdardinier** [viperproject/carbon#381]
The following program is accepted by Silicon, but makes Carbon crash.

```
function g(x: Int, y: Int): Bool

function f(x: Int): Bool
{
  exists y:Int :: { g(x, y) } g(x, y)
}
```

Carbon crashes with the following message:

> ERROR: The following exception occured in ViperServer: java.util.NoSuchElementException: key not found: g#frame

**Comment by gauravpartha** [comment]
Fixed in https://github.com/viperproject/carbon/pull/398
