### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by niomaster** [viperproject/carbon#413]
Hello! I recently updated my computer, and carbon now forwards this message from Boogie:

```
carbon 1.0
carbon found 1 error in 1.95s:
  [0] An internal error occurred. Found an unparsable output from Boogie: No usable version of libssl was found (<no position>)
```

Indeed, running boogie results in the same message:

```
$ ./Boogie 
No usable version of libssl was found
Aborted (core dumped)
```

This is with the boogie that is distributed with the viper release (2022.2). 

Looking at `strace` it seems Boogie is expecting `libssl` version 1.0/1.1, which is no longer included with my distribution (Ubuntu 22.04), I can only easily install `libssl3`. I [think](https://github.com/viperproject/boogie-builder/blob/3ff128f73e3e51c5013f7e787e4a35dc2a3d8ea2/.github/workflows/build.yml#L24-L27) viper's boogie is built with .net 3.1, which expects libssl1 and not 3 ([see also here](https://github.com/dotnet/runtime/issues/67986#issuecomment-1098474211)). 

Pratically I would suggest to either:

* Update to .NET 6+, since .NET 3.1 will be EOL in december anyway, or;
* Distribute `libssl1.1` with Boogie

In case anyone encounters this issue and wants a hacky workaround, it seems installing `libssl1.1` is the only action required, e.g. for ubuntu [from the previous LTS](https://packages.ubuntu.com/focal/libssl1.1)

**Comment by gauravpartha** [comment]
Thanks a lot for the information and the temporary workaround. I don't think the (fairly old) Boogie version we are working with is compatible with .NET 6 (although there would only be minimal changes required to Boogie). Ideally, we would update to the newest Boogie version. One thing making this update somewhat nontrivial is that the Carbon counterexamples feature breaks down with the newest Boogie version and requires some changes on the Carbon side.

**Comment by gauravpartha** [comment]
We have upgraded Carbon to use Boogie 2.15.9 in the merged PR https://github.com/viperproject/carbon/pull/441, which is based on .NET 6. So, this problem should hopefully be solved.
