### ISSUE TITLE
Quantified Let Binding without trigger causes internal error

### ISSUE THREAD

**Issue by dewert99** [viperproject/carbon#415]
The following program:
```
method test3(xs: Set[Bool]) {
  inhale forall b1: Bool :: let ys == (xs) in (b1 in ys ==> true)
}
```
produces a java.lang.RuntimeException: Internal Error: variable `ys` is not defined.

**Comment by marcoeilers** [comment]
This error no longer occurs, presumably because of fixes in the trigger inference (https://github.com/viperproject/silver/pull/753), so I'll close the issue.
