### ISSUE TITLE
Missing libssl1.1 on Ubuntu 22.04

### ISSUE THREAD

**Issue by fpoli** [viperproject/carbon#432]
The Carbon verifier doesn't work on Ubuntu 22.04. The error message is
```
carbon 1.0
carbon found 1 error in 1.55s:
  [0] An internal error occurred. Found an unparsable output from Boogie: No usable version of libssl was found (<no position>)
```

The reason is that Ubuntu 22.04 now comes with `libssl3`, no longer `libssl1.1`, but the Boogie binary apparently requires `libssl1.1`.

A temporary solution for Ubuntu 22.04 users is to [manually install libssl1.1](https://stackoverflow.com/a/72633324/2491528). However, the proper solution would be to release Boogie binaries for both Ubuntu 22.04 and Ubuntu 20.04, building them in https://github.com/viperproject/boogie-builder with both the ubuntu-22.04 and ubuntu-20.04 github runners. Such solution would also require changes to the Viper IDE, which should detect wether it's running on Ubuntu 22.04 or not (CC @ArquintL).

(We are having a similar issue with Prusti: https://github.com/viperproject/prusti-dev/issues/1167.)

**Comment by gauravpartha** [comment]
Related issue https://github.com/viperproject/carbon/issues/413 (I'll leave both open for now).

**Comment by fpoli** [comment]
Just a heads up: `ubuntu-latest` is going to start using Ubuntu 22.04 in these weeks. See [this announcement](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/). We already noticed it in Prusti. It means that Carbon/Boogie/viper-ide workflows that use `ubuntu-latest` are going to deploy the boogie compiled for Ubuntu 22.04, which might not work on Ubuntu 20.04 (CC @ArquintL).

**Comment by gauravpartha** [comment]
Thanks for the heads up. @marcoeilers has recently made some changes that should enable an upgrade of Boogie with .NET 6. I'll check soon whether we can upgrade Boogie and whether we then can get rid of the libssl1.1 dependency.

**Comment by gauravpartha** [comment]
We have upgraded Carbon to use Boogie 2.15.9 in the merged PR https://github.com/viperproject/carbon/pull/441, which is based on .NET 6. So, this problem should hopefully be solved.

**Comment by fpoli** [comment]
I confirm that Carbon now works on an Ubuntu 22.04 OS *without* `libssl1.1`. Thanks!
