### ISSUE TITLE
Labelled old expressions are not checked to be guaranteed to be on the same path as the label

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#89]
> Created by **@alexanderjsummers** on 2016-01-05 17:00

The results are that nothing can be proved about them in cases in which the label is not encountered, so the behaviour isn't too bad. This should probably be fixed at the Silver level.

See all/old/branching_labelled_old test case

**Comment by gauravpartha** [comment]
This has been fixed in 2b9ac113e58b2091a818f8cae9cce2826d2a106d. It was fixed at the Boogie encoding level using auxiliary Boolean variables tracking whether a label has been defined or not.
